### ISSUE TITLE
Taking over

### ISSUE THREAD

**Issue by guicho271828** [guicho271828/CL-CUDD#1]
@rpgoldman , apparantly @Neronus seems inactive for years, so I'm considering taking it over.
Now my version pulls the latest CUDD, build it, grovel it and sets up the foreign library. (latest tarball is download by curl, therefore there is no need to install it manually) It also follows a modern style and has an example in the `test/` directory.

I'm more interested in using ZDD, so I have to extend the library.

**Comment by rpgoldman** [comment]
That sounds great, thanks.

I tried using this, but it was not finished enough and I had a tight deadline, so I had to drop it and use the perl interface to CUDD instead.

I think what would make it most useful would be to create a CLOS layer around the FFI, with CLOS objects representing the DDs and methods for automatically translating back and forth.  Otherwise, you are constantly messing with untyped pointers, and it's easy to crash your lisp image with little useful feedback.

Unfortunately, the CFFI documentation about how to do this (unless it has substantially improved in the last 2 years) is very sketchy.

**Comment by guicho271828** [comment]
AFAIK CLOS layer is already finished in the original version. I also found `zero-node` incorrectly returns arithmetic zero for BDD (not logical zero), which causes memory corruption, so I fixed it. Other than that, all raw-pointer manipulations look hidden.

What's not available are variable reordering, zdd, CLOS methods for visualization (dot output).

**Comment by rpgoldman** [comment]
I'll have to look again; it's been a few years.  I recall thinking it would be handy to have CLOS objects that would correspond to specific kinds of DD, for example (like cubes).  And I'm not sure that the garbage collection was all handled.  But as I said, it's been a long time since I tried to use this.

**Comment by guicho271828** [comment]
Now I mostly finished the ZDD part and the documentation.

**Comment by guicho271828** [comment]
higher level CLOS API sounds great.

**Comment by guicho271828** [comment]
I rather plan to implement a MOP metaclass that stores every information into a ZDD. Only immediate data are stored in a VSOP representation.

**Comment by guicho271828** [comment]
now in Quicklisp.
